name: CMake CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-type: [ Release ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: jacobmarshall/setup-cmake@v1

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DBUILD_TESTS=ON ../
        cmake --build .

    - name: Run tests
      run: |
        cd build
        ctest -C ${{ matrix.build-type }} --output-on-failure
